version: 2.1

jobs:
  checkov:
    docker:
      - image: python@sha256:$PYTHON_CI_IMAGE
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: checkov-{{ .Environment.CHECKOV_VERSION }}
      - run:
          name: Install Checkov
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install checkov
      - save_cache:
          key: checkov-{{ .Environment.CHECKOV_VERSION }}
          paths:
            - ".venv"
      - run:
          name: Run Checkov against repo
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            cd ~/repo/
            checkov -d . --skip-check CKV_DOCKER_3,CKV_DOCKER_2,CKV_CIRCLECIPIPELINES_6

  git-leaks:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Scan for gitLeaks
          command: |
            docker run -v ~/repo:/path zricethezav/gitleaks:latest detect --source="/path" -v


  publish-repl:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and tag repl image
          command: |
            cd ~/repo/repl
            docker build -t repl:$CIRCLE_TAG .
            docker tag repl:$CIRCLE_TAG repl:latest
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" \
              --password-stdin
            docker push repl:$CIRCLE_TAG
            docker push repl:latest

workflows:
  CI:
    jobs:
      - checkov
      - git-leaks
  CD:
    jobs:
      - publish-repl:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/
