version: 2.1

jobs:
  checkov:
    docker:
      - image: python@sha256:$PYTHON_CI_IMAGE
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: checkov-{{ .Environment.CHECKOV_VERSION }}
      - run:
          name: Install Checkov
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install checkov
      - save_cache:
          key: checkov-{{ .Environment.CHECKOV_VERSION }}
          paths:
            - ".venv"
      - run:
          name: Run Checkov against repo
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            cd ~/repo/
            checkov -d . --skip-check CKV_DOCKER_3,CKV_DOCKER_2

  git-leaks:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Scan for gitLeaks
          command: |
            docker run -v ~/repo:/path zricethezav/gitleaks:latest detect --source="/path" -v

workflows:
  ci:
    jobs:
      - checkov
      - git-leaks
